### ISSUE TITLE
The `html` method is not ensuring browser closing and deletion.

### ISSUE THREAD

**Issue by leandrosardi** [connection-sphere/adspower-client#1]
## Problem

```bash
2023-12-05 18:27:23: Scraping Indeed Example

2023-12-05 18:27:23: Scraping Miami... 2023-12-05 18:27:33 INFO Selenium [:logger_info] Details on how to use and modify Selenium logger:
  https://selenium.dev/documentation/webdriver/troubleshooting/logging

2023-12-05 18:27:33 WARN Selenium [:add_option] [DEPRECATION] Options#add_option for w3c or browser specific capabilities is deprecated. Use applicable attribute accessors or pass into constructor instead. 
2023-12-05 18:27:33 WARN Selenium [:option_symbols] [DEPRECATION] debuggerAddress as option is deprecated. Use debugger_address instead. 
done
2023-12-05 18:27:40: Scraping Tampa... 2023-12-05 18:27:46 WARN Selenium [:add_option] [DEPRECATION] Options#add_option for w3c or browser specific capabilities is deprecated. Use applicable attribute accessors or pass into constructor instead. 
2023-12-05 18:27:46 WARN Selenium [:option_symbols] [DEPRECATION] debuggerAddress as option is deprecated. Use debugger_address instead. 
/home/leandro/code/adspower-client/lib/adspower-client.rb:71:in `delete': Error: {"code"=>-1, "msg"=>"[jc913k5] is being used by [leandro.sardi@expandedventure.com] mailbox users and cannot be deleted"} (RuntimeError)
	from /home/leandro/code/adspower-client/lib/adspower-client.rb:137:in `html'
	from indeed.rb:14:in `block in <main>'
	from indeed.rb:12:in `each'
	from indeed.rb:12:in `<main>'
```

**Comment by leandrosardi** [comment]
Fixed.
